### PR TITLE
feat: add docker image

### LINKED ISSUE #45: Create docker image
Create a docker image to be able to easily deploy on servers

### PR DESCRIPTION
**Pull request by sebaplaza**
Closes #45

### CODE REVIEW

**Review by m1guelpf — CHANGES_REQUESTED** [review]
This looks great! However, I'm concerned with the `.config/chatgpt.json` file confusing someone, as it's not super clear that it's to do with the Docker setup. Could we maybe move it to a `.docker` folder instead, along with the Dockerfile?

**Comment by sebaplaza** [comment]
I'll work to generate an official docker image with every release

Currently, the `docker-compose` provided needs to clone the repository and manually build the image.

If we build a official docker image, we could just have an example in the README.md with the docker usage.

About `Dockerfile` location, we need to keep it in the root folder, because of the docker build context, where all needed files (src/) cannot be in an upper folder lever.

**Comment by sebaplaza** [comment]
You're right @lxy1992!
I just cleaned the alpine useless build deps.

About playwright, its essential to run this package.

**Comment by sebaplaza** [comment]
@m1guelpf done.

I updated the repository to generate an official docker image on every release.

Now the docker example is included in README.md

**Review by m1guelpf — APPROVED** [review]

**Pull request merged**
