### PR TITLE
Fix issue with accessing the .env file on machines with Apple silicon

### PR DESCRIPTION
**Pull request by marcelgruber**
Should fix issue #9

### CODE REVIEW

**Comment by realies** [comment]
@marcelgruber, appears to work fine here without this patch

**Comment by marcelgruber** [comment]
@realies which OS / architecture are you using?

**Review by m1guelpf — CHANGES_REQUESTED** [review]
This breaks `go run` with the following error: `Couldn't load .env file: open /var/folders/86/3vyx8x4j28n7b90791wmx2gr0000gn/T/go-build3392845733/b001/exe/.env: no such file or directory`

**Comment by m1guelpf** [comment]
Don't really get the proposed solution, the `.env` file should be in the directory we're running the command from, not in the directory of the executable. These often are the same, but don't need to be.

**Comment by realies** [comment]
@marcelgruber, darwin on m1

**Comment by rayzhudev** [comment]
If I may chip in, the problem occurs when opening the binary via the file explorer, which makes the pwd the root directory. This change makes it so that you don't have to open the executable from the terminal, you can do it from the file explorer.

**Comment by m1guelpf** [comment]
Updated the README with more details on how to run the binary, that should fix this I think.

**Pull request closed without merging**
